name: Build Docs

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
  pull_request:
    branches:
      - master
    paths:
      - "docs/**"
  workflow_dispatch:

jobs:
  build-docs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements/docs.txt

      - name: Build docs
        run: |
          make -C ./docs html

      - name: Upload sphinx documentation
        uses: actions/upload-artifact@v3
        with:
          name: sphinx-docs
          path: ./docs/_build
          retention-days: 30

  deploy-docs:
    if: github.ref == 'refs/heads/master'
    name: Deploy documentation
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - name: Download sphinx documentation
        uses: actions/download-artifact@v3
        with:
          name: sphinx-docs
          path: ./build

      - name: Add files to bypass jekyll build
        run: |
          touch build/.nojekyll

      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: build
